# Data Processing

In [3]:
import pandas as pd

file_name = "RING_SAATLERI.xlsx"

In [5]:
dfs = pd.read_excel(file_name, sheet_name=None)

In [10]:
dfs["HAFTA SONU"]

,RÄ°NG 1 - HAFTA SONU,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,1100,1030,1050,960,950,810,B4,B5,170,210,...,210,170,B5,B4,810,950,960,1050,1030,1100
1,07:00:00,07:04:00,07:06:00,07:07:00,07:08:00,07:08:00,07:08:00,07:08:00,07:09:00,07:10:00,...,07:16:00,07:17:00,07:18:00,07:18:00,07:19:00,07:20:00,07:21:00,07:22:00,07:23:00,07:25:00
2,07:20:00,07:24:00,07:26:00,07:27:00,07:28:00,07:28:00,07:28:00,07:28:00,07:29:00,07:30:00,...,07:36:00,07:37:00,07:38:00,07:38:00,07:39:00,07:40:00,07:41:00,07:42:00,07:43:00,07:45:00
3,07:40:00,07:44:00,07:46:00,07:47:00,07:48:00,07:48:00,07:48:00,07:48:00,07:49:00,07:50:00,...,07:56:00,07:57:00,07:58:00,07:58:00,07:59:00,08:00:00,08:01:00,08:02:00,08:03:00,08:05:00
4,08:00:00,08:04:00,08:06:00,08:07:00,08:08:00,08:08:00,08:08:00,08:08:00,08:09:00,08:10:00,...,08:16:00,08:17:00,08:18:00,08:18:00,08:19:00,08:20:00,08:21:00,08:22:00,08:23:00,08:25:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,20:30:00,20:31:00,20:32:00,20:33:00,20:34:00,20:35:00,20:36:00,1900-01-05 08:37:00,20:38:00,20:39:00,...,20:43:00,20:45:00,20:46:00,20:47:00,20:48:00,20:49:00,20:50:00,NaN,NaN,NaN
85,21:00:00,21:01:00,21:02:00,21:03:00,21:04:00,21:05:00,21:06:00,1900-01-06 03:07:00,21:08:00,21:09:00,...,21:13:00,21:15:00,21:16:00,21:17:00,21:18:00,21:19:00,21:20:00,NaN,NaN,NaN
86,21:30:00,21:31:00,21:32:00,21:33:00,21:34:00,21:35:00,21:36:00,1900-01-06 21:37:00,21:38:00,21:39:00,...,21:43:00,21:45:00,21:46:00,21:47:00,21:48:00,21:49:00,21:50:00,NaN,NaN,NaN
87,22:00:00,22:01:00,22:02:00,22:03:00,22:04:00,22:05:00,22:06:00,1900-01-07 16:07:00,22:08:00,22:09:00,...,22:13:00,22:15:00,22:16:00,22:17:00,22:18:00,22:19:00,22:20:00,NaN,NaN,NaN
88,22:30:00,22:31:00,22:32:00,22:33:00,22:34:00,22:35:00,22:36:00,1900-01-08 10:37:00,22:38:00,22:39:00,...,22:43:00,22:45:00,22:46:00,22:47:00,22:48:00,22:49:00,22:50:00,NaN,NaN,NaN